### PR TITLE
Feat: Simple website with background video

### PR DESCRIPTION
**Pull request by TheInspiredConjurer**
- Create simple website background video.
- Navbar is responsive.
- Add Play  / Pause button for video controls.

Fixes issue #28

### CODE REVIEW

**Comment by KIET7UKE** [comment]
Can you share the screenshots of the website
or
Deploy somewhere and send the link

**Comment by TheInspiredConjurer** [comment]
> Can you share the screenshots of the website or Deploy somewhere and send the link

Sure... I hadn't published it, because I didn't think it was needed, but since you asked, here it is:

https://astonishing-mochi-e57084.netlify.app/

**Comment by KIET7UKE** [comment]
Damn, Good work @TheInspiredConjurer Appreciated.

**Comment by TheInspiredConjurer** [comment]
Thanks a lot!

**Pull request merged**
